stages:
  - version
  - lint
  - build

version:
  stage: version
  image: alpine/git:1.0.7
  script: git describe --always --tags --dirty >> version
  artifacts:
    paths:
    - version
  only:
    - main

lint:
  stage: lint
  image: node:18.16-alpine
  script:
    - npm i
    - npx eslint .

build-test:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  script:
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
      --dockerfile $CI_PROJECT_DIR/Dockerfile \
      --no-push
  except:
    - main
